name: Build and Test Workflow

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test App
    runs-on: macos-latest
    strategy:
      matrix:
        xcode: [16.2] # Add more versions as needed

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Set Xcode version
        run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app

      - name: Build app
        run: |
          set -e
          cd Sample
          xcodebuild build -scheme Sample -destination 'platform=macOS'
