name: Build and Test Workflow

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and Test App
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cocoapods
          key: ${{ runner.os }}-cocoapods-${{ hashFiles('**/Podfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-cocoapods-

      - name: Build app
        run: |
          cd Sample
          xcodebuild build \
          -scheme Sample \
          -destination 'platform=macOS'

      - name: Run Unit Tests
        run: |
          xcodebuild test \
          -scheme Sample \
          -destination 'platform=macOS'
